### ISSUE TITLE
Can you add the code for the Umazegoal env def and also to reproduce the results for it as well?

### ISSUE THREAD

**Issue by quanvuong** [Ji4chenLi/Multi-Task-Batch-RL#1]

**Comment by Ji4chenLi** [comment]
Codes added.

**Comment by quanvuong** [comment]
In the README, under the section "Reproducing Results Fig. 8 and Fig. 13 in our paper." you list the index for each environment, do you have to do something similar for UmazeGoal? What should we do to run with the ground truth reward function on this environment. Add these to the README.

**Comment by Ji4chenLi** [comment]
Added similar thing for UmazeGoal-M in README.

In the section of "Reproduce the results in Fig. 6 in our paper", I have list the commands to run with the ground truth reward function on UmazeGoal-M. There is nothing else should be done. 

The ground truth rewards for each state-action pair are simply calculated a function inside trainer.py. 
https://github.com/Ji4chenLi/Multi-Task-Batch-RL/blob/a9d61093445b71538e8e7e800bf179d2a274b1dc/full_model_ground_truth_label/trainer.py#L87-L95
